
## Assignment 4

### Q1: Build Your Personalized Knowledge Base

In [1]:
import pandas as pd

fixed_entries = [
    {
        "question": "what is the annual fee", 
        "answer": "The annual fee is Rs 500.",
        "keywords": "fee cost price charge", 
        "category": "billing"
    },
    
    {
        "question": "how to reset password", 
        "answer": "Go to Settings > Reset Password.",
        "keywords": "password reset login", 
        "category": "account"
    },
    {
        "question": "what are your working hours", 
        "answer": "We are open 9 AM to 5 PM.",
        "keywords": "hours timing open time", 
        "category": "general"
    },
    {
        "question": "how can i pay the fee", 
        "answer": "You can pay via UPI, card, or net banking.",
        "keywords": "pay payment upi fee", 
        "category": "billing"
    },
]

personalized_entries = [
    {
        "question": "how do I update my registered mobile number",
        "answer": "Go to Profile Settings > Personal Info to update your mobile number.",
        "keywords": "mobile number update profile phone",
        "category": "account"
    },
    {
        "question": "where is the main campus located",
        "answer": "The main campus is located at the central block.",
        "keywords": "location campus address where",
        "category": "general"
    }
]

df_faq = pd.DataFrame(fixed_entries + personalized_entries)
display(df_faq)

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge,billing
1,how to reset password,Go to Settings > Reset Password.,password reset login,account
2,what are your working hours,We are open 9 AM to 5 PM.,hours timing open time,general
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",pay payment upi fee,billing
4,how do I update my registered mobile number,Go to Profile Settings > Personal Info to upda...,mobile number update profile phone,account
5,where is the main campus located,The main campus is located at the central block.,location campus address where,general

### Q2 & Q6: Generate and Score a Hypothesis with Tie Handling

In [2]:
def score_and_match_query(query, df):
    query_words = set(query.lower().split())
    scores = []
    for keywords_str in df["keywords"]:
        kw_set = set(keywords_str.lower().split())
        score = len(query_words.intersection(kw_set))
        scores.append(score)
        
    df_scored = df.copy()
    df_scored["score"] = scores
    max_score = df_scored["score"].max()
    
    if max_score == 0:
        print(f"Query: '{query}' -> No matching entries found.")
        return pd.DataFrame()
    
    tied_matches = df_scored[df_scored["score"] == max_score]
    print(f"Query: '{query}' (Max Score: {max_score})")
    print(f"Found {len(tied_matches)} matching entry/entries:")
    return tied_matches[["question", "answer", "category", "score"]]

### Q3: Filter by Same Category

In [3]:
def same_category(category_name, df):
    matched = df[df["category"] == category_name]
    return matched["question"].tolist()

sample_category = "account"
cat_questions = same_category(sample_category, df_faq)
print(f"Category '{sample_category}': {cat_questions}")

Category 'account': ['how to reset password', 'how do I update my registered mobile number']

### Q4: Keyword Modification and CSV Export

In [4]:
target_index = 0
new_keyword = input("Enter a new keyword to add to the first entry: ").strip()
if not new_keyword:
    new_keyword = "portal"

current_keywords = df_faq.loc[target_index, "keywords"]
df_faq.loc[target_index, "keywords"] = current_keywords + " " + new_keyword

roll_number = "1022045"
csv_filename = f"{roll_number}_faq_data.csv"
df_faq.to_csv(csv_filename, index=False)
display(df_faq.loc[[target_index]])

,question,answer,keywords,category
0,what is the annual fee,The annual fee is Rs 500.,fee cost price charge anirudh,billing

### Q5: Groupby Category Count

In [5]:
category_counts = df_faq.groupby("category").size().reset_index(name="count")
display(category_counts)

  category  count
0  account      2
1  billing      2
2  general      2

### Q6: Demonstration of Ties and Non-Ties

In [6]:
display(score_and_match_query("fee", df_faq))
display(score_and_match_query("password", df_faq))

Query: 'fee' (Max Score: 1)
Found 2 matching entry/entries:

,question,answer,category,score
0,what is the annual fee,The annual fee is Rs 500.,billing,1
3,how can i pay the fee,"You can pay via UPI, card, or net banking.",billing,1

Query: 'password' (Max Score: 1)
Found 1 matching entry/entries:

                question                            answer category  score
1  how to reset password  Go to Settings > Reset Password.  account      1